# Generated by Django 5.1 on 2024-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
