# Generated by Django 5.1 on 2024-09-17 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ref_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('clothing', 'Clothing'), ('medication', 'Medication')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
